### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by ThijsMaas** [AbeelLab/ptolemy#1]
Hi,
I would love to see what ptolemy can do, but I'm not sure how to get in running.
My guess is to compile it with sbt, as there is a build script.
But when I run sbt compile, or sbt run in the repository I get these errors:

> [info] Loading project definition from \~/ptolemy/project
[info] Loading settings from build.sbt ...
[info] Set current project to Ptolemy (in build file:~/ptolemy/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Compiling 16 Scala sources and 3 Java sources to \~/ptolemy/target/scala-2.12/classes ...
[error] \~/ptolemy/src/main/scala/cli/Ptolemy.scala:32:39: not found: value msa
[error]         case "run-msa"             => msa.RunMSA.main(args.drop(1))
[error]                                       ^
[error] ~p/ptolemy/src/main/scala/cli/Ptolemy.scala:33:55: object HighLevelVariantCaller is not a member of package variant_calling
[error]         case "variant-calling"     => variant_calling.HighLevelVariantCaller.main(args.drop(1))
[error]                                                       ^
[error] ~/ptolemy/src/main/scala/cli/Ptolemy.scala:34:39: not found: value parental_perspective
[error]         case "parents"             => parental_perspective.CharacterizeWithParents.main(args.drop(1))
[error]                                       ^
[error] three errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 8 s, completed Jul 6, 2018, 2:58:26 PM

I don't know much about scala, but there seem to be some issues here?

Thanks in advance,
Thijs

**Comment by ansalaza** [comment]
Hi ThijsMaas,

It's been on my to-do list to add more info in the github page...

The README has a brief overview along with a tutorial + testing data. There is a jar file under releases which you can use for taking Ptolemy for spin.

Let me know if you run to more problems.

Best,

Alex
