### ISSUE TITLE
Missing fields from GFA specifications

### ISSUE THREAD

**Issue by jlobatop** [AbeelLab/ptolemy#6]
After running the test cases available in the repository, I obtained the graph, thus validating the installation. However, when trying to analyze the `.gfa` output, I think that there is one missing field in the Path Lines. 

As detailed in the [format specifications](http://gfa-spec.github.io/GFA-spec/GFA1.html#required-fields-5), there are 4 required fields: `RecordType` (the leading `P` in the line), `PathName`, `SegmentNames` (delimited by commas) and the  `Overlaps`. However, when looking at the Ptolemy output graph, I just get three fields (see either the extract below

> P	SK1_chrVII	1722+,1580+,1934+,...,1501+,1502+,1503+

or the [full graph](https://github.com/AbeelLab/ptolemy/files/4100439/ptolemy.txt) - whose extension has been changed to `.txt` so it can be uploaded to the issue). 

One solution will be to fill the field with `*` as that will already match the format specification, not requiring the CIGAR strings.

**Comment by aysunrhn** [comment]
Hi Javier,

I've been trying to make a couple of changes in Ptolemy, I have also modified the code to output `gfa` file with path lines that end with `*` so it is valid. Is it possible if you could check if the attached `jar` is working for you? Just want to make sure I'm on the right path, I'd really appreciate it.

[ptolemy-0.1.1.tar.gz](https://github.com/AbeelLab/ptolemy/files/4230831/ptolemy-0.1.1.tar.gz)

**Comment by jlobatop** [comment]
Hi Aysun,
I have checked and now the `.gfa`  output files already have the `*` field so it complies with the required fields. Thus, the issue can be closed, good work!
